heat_template_version: queens

description: adding persistent mount options to fstab to back swift luns from element

parameters:
  servers:
    type: json
  local_disk:
    type: string
  mount_point:
    type: string
  fs_type:
    type: string
  fs_options:
    type: string
  disk_check:
    type: string
  DeployIdentifier:
    type: string

resources:
  CustomExtraConfig:
     type: OS::Heat::SoftwareConfig
     properties:
       group: script
       config:
         str_replace:
           template: |
             #!/bin/sh
             set -x
             if [[ `hostname` = *"controller"* ]]
             then
             sed -i '$d' /etc/fstab
             echo "_LOCAL_DISK_ _MOUNT_POINT_ _FS_TYPE_ _FS_OPTIONS_ _DISK_CHECK_" >> /etc/fstab
             mount -a
             fi
           params:
             _LOCAL_DISK_: {get_param: local_disk}
             _MOUNT_POINT_: {get_param: mount_point}
             _FS_TYPE_: {get_param: fs_type}
             _FS_OPTIONS_: {get_param: fs_options}
             _DISK_CHECK_: {get_param: disk_check}

  CustomExtraDeployments:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      servers:  {get_param: servers}
      config: {get_resource: CustomExtraConfig}
      actions: ['CREATE','UPDATE']
      input_values:
        deploy_identifier: {get_param: DeployIdentifier}

